import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from 'react';
import "./globals.css";
import { ThemeProvider } from "@/hooks/use-theme";
import { ExampleStateProvider } from './ExampleStateProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "默默学开发",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="system" storageKey="theme">
          <ExampleStateProvider>
            <div className="portal-layout">
              <main>{children}</main>
            </div>
            <div className="text-center text-sm text-gray-500 mt-10"><a href="https://beian.miit.gov.cn/" target="_blank">湘ICP备20014625号-1</a></div>
          </ExampleStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
